AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Kitchenmate Backend API

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 60
    MemorySize: 512

Resources:
  KitchenmateBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - S3ReadPolicy:
            BucketName: naveen-kitchenmate-bucket
        - S3CrudPolicy:
            BucketName: naveen-kitchenmate-bucket
      CodeUri: .
      Handler: lambda.handler

      Environment:
        Variables:

          COMPANY_NAME: "kitchenmate"

          DB_HOST: "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
          DB_NAME: "naveen_retail_db"
          DB_PASS: "EiE3uV2QJXx9Y83O"
          DB_PORT: "4000"
          DB_USER: "kD4vuBdkSJw4mLY.root"
          AWS_BUCKET_NAME: "naveen-kitchenmate-bucket"

          DEFAULT_FOOD_IMG: ""

          GMAIL_ID: ""
          GMAIL_PASSKEY: ""

      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

        Proxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

  DailyReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:StartQuery
                - logs:GetQueryResults
                - logs:DescribeLogGroups
              Resource: "*"
      CodeUri: .
      Handler: dailyReport.handler
      Runtime: nodejs20.x
      Timeout: 300
      MemorySize: 256

      Environment:
        Variables:
          GMAIL_ID: "xbotlistautomation@gmail.com"
          GMAIL_PASSKEY: "omwk ywam xgpp qbdl"
          REPORT_EMAIL: "naveenkrishnab08@zohomail.in"
          LOG_GROUP_NAME: "/aws/lambda/kitchenmate-backend-KitchenmateBackendFunction-uJdzgwiHiJMm"

      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(25 18 * * ? *)


Outputs:
  ApiUrl:
    Description: HTTP API endpoint
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"